bio_genus = {
    "$Codex_Ent_Aleoids_Genus_Name;": {"name": "Aleoida", "distance": 150},
    "$Codex_Ent_Bacterial_Genus_Name;": {"name": "Bacterium", "distance": 500},
    "$Codex_Ent_Cactoid_Genus_Name;": {"name": "Cactoida", "distance": 300},
    "$Codex_Ent_Clypeus_Genus_Name;": {"name": "Clypeus", "distance": 150},
    "$Codex_Ent_Conchas_Genus_Name;": {"name": "Concha", "distance": 150},
    "$Codex_Ent_Cone_Name;": {"name": "Bark Mound", "distance": 100},
    "$Codex_Ent_Electricae_Genus_Name;": {"name": "Electricae", "distance": 1000},
    "$Codex_Ent_Fonticulus_Genus_Name;": {"name": "Fonticulua", "distance": 500},
    "$Codex_Ent_Fumerolas_Genus_Name;": {"name": "Fumerola", "distance": 100},
    "$Codex_Ent_Fungoids_Genus_Name;": {"name": "Fungoida", "distance": 300},
    "$Codex_Ent_Ground_Struct_Ice_Name;": {"name": "Crystalline Shards", "distance": 100},
    "$Codex_Ent_Osseus_Genus_Name;": {"name": "Osseus", "distance": 800},
    "$Codex_Ent_Recepta_Genus_Name;": {"name": "Recepta", "distance": 150},
    "$Codex_Ent_Seed_Name;": {"name": "Brain Tree", "distance": 100},
    "$Codex_Ent_Shrubs_Genus_Name;": {"name": "Frutexa", "distance": 150},
    "$Codex_Ent_Sphere_Name;": {"name": "Anemone", "distance": 100},
    "$Codex_Ent_Stratum_Genus_Name;": {"name": "Stratum", "distance": 500},
    "$Codex_Ent_Tube_Name;": {"name": "Sinuous Tubers", "distance": 100},
    "$Codex_Ent_Tubus_Genus_Name;": {"name": "Tubus", "distance": 800},
    "$Codex_Ent_Tussocks_Genus_Name;": {"name": "Tussock", "distance": 200},
    "$Codex_Ent_Vents_Name;": {"name": "Amphora Plant", "distance": 100},
}

# journal_id: (localized name, base value, atmosphere, maximum gravity, maximum temp, minimum temp, volcanism, planet, region, extra)
bio_types = {
    "$Codex_Ent_Aleoids_Genus_Name;": {
        "$Codex_Ent_Aleoids_01_Name;": ("Aleoida Arcus", 7252500, ["CarbonDioxide", "CarbonDioxideRich"], 0.275, 180.0, 175.0, None, ["Rocky body", "High metal content body"], None, None),
        "$Codex_Ent_Aleoids_02_Name;": ("Aleoida Coronamus ", 6284600, ["CarbonDioxide", "CarbonDioxideRich"], 0.275, 190.0, 180.0, None, ["Rocky body", "High metal content body"], None, None),
        "$Codex_Ent_Aleoids_03_Name;": ("Aleoida Spica", 3385200, ["Ammonia"], 0.275, None, None, None, ["Rocky body", "High metal content body"], ["!scutum-centaurus"], None),
        "$Codex_Ent_Aleoids_04_Name;": ("Aleoida Laminiae", 3385200, ["Ammonia"], 0.275, None, None, None, ["Rocky body", "High metal content body"], ["scutum-centaurus"], None),
        "$Codex_Ent_Aleoids_05_Name;": ("Aleoida Gravis", 12934900, ["CarbonDioxide", "CarbonDioxideRich"], 0.275, 195.0, 190.0, None, ["Rocky body", "High metal content body"], None, None)
    },
    "$Codex_Ent_Bacterial_Genus_Name;": {
        "$Codex_Ent_Bacterial_01_Name;": ("Bacterium Aurasus", 1000000, ["CarbonDioxide", "CarbonDioxideRich"], None, None, None, None, ["Rocky body", "High metal content body"], None, None),
        "$Codex_Ent_Bacterial_02_Name;": ("Bacterium Nebulus", 9116600, ["Helium"], None, None, None, None, None, None, None),
        "$Codex_Ent_Bacterial_03_Name;": ("Bacterium Scopulum", 4934500, ["Neon", "NeonRich"], None, None, None, ["carbon dioxide", "methane"], None, None, None),
        "$Codex_Ent_Bacterial_04_Name;": ("Bacterium Acies", 1000000, ["Neon", "NeonRich"], None, None, None, None, None, None, None),
        "$Codex_Ent_Bacterial_05_Name;": ("Bacterium Vesicula", 1000000, ["Argon", "ArgonRich"], None, None, None, None, None, None, None),
        "$Codex_Ent_Bacterial_06_Name;": ("Bacterium Alcyoneum", 1658500, ["Ammonia"], None, None, None, None, ["Rocky body", "High metal content body"], None, None),
        "$Codex_Ent_Bacterial_07_Name;": ("Bacterium Tela", 1949000, "Any", None, None, None, ["helium", "iron", "silicate", "ammonia"], None, None, None),
        "$Codex_Ent_Bacterial_08_Name;": ("Bacterium Informem", 8418000, ["Nitrogen"], None, None, None, None, None, None, None),
        "$Codex_Ent_Bacterial_09_Name;": ("Bacterium Volu", 7774700, ["Oxygen"], None, None, None, None, None, None, None),
        "$Codex_Ent_Bacterial_10_Name;": ("Bacterium Bullaris", 1152500, ["Methane", "MethaneRich"], None, None, None, None, None, None, None),
        "$Codex_Ent_Bacterial_11_Name;": ("Bacterium Omentum", 4638900, ["Neon", "NeonRich"], None, None, None, ["nitrogen", "ammonia"], None, None, None),
        "$Codex_Ent_Bacterial_12_Name;": ("Bacterium Cerbrus", 1689800, ["Water", "WaterRich", "SulphurDioxide"], None, None, None, None, None, None, None),
        "$Codex_Ent_Bacterial_13_Name;": ("Bacterium Verrata", 3897000, ["Neon", "NeonRich"], None, None, None, ["water"], None, None, None),
    },
    "$Codex_Ent_Cactoid_Genus_Name;": {
        "$Codex_Ent_Cactoid_01_Name;": ("Cactoida Cortexum", 3667600, ["CarbonDioxide", "CarbonDioxideRich"], 0.275, 195.0, 180.0, None, ["Rocky body", "High metal content body"], ["orion-cygnus"], None),
        "$Codex_Ent_Cactoid_02_Name;": ("Cactoida Lapis", 2483600, ["Ammonia"], 0.275, None, None, None, ["Rocky body", "High metal content body"], ["scutum-centaurus"], None),
        "$Codex_Ent_Cactoid_03_Name;": ("Cactoida Vermis", 16202800, ["Water", "WaterRich"], 0.275, None, None, None, ["Rocky body", "High metal content body"], None, None),
        "$Codex_Ent_Cactoid_04_Name;": ("Cactoida Pullulanta", 3667600, ["CarbonDioxide", "CarbonDioxideRich"], 0.275, 195.0, 180.0, None, ["Rocky body", "High metal content body"], ["perseus"], None),
        "$Codex_Ent_Cactoid_05_Name;": ("Cactoida Peperatis", 2483600, ["Ammonia"], 0.275, None, None, None, ["Rocky body", "High metal content body"], ["outer"], None),
    },
    "$Codex_Ent_Clypeus_Genus_Name;": {
        "$Codex_Ent_Clypeus_01_Name;": ("Clypeus Lacrimam", 8418000, ["CarbonDioxide", "CarbonDioxideRich", "Water", "WaterRich"], 0.275, None, 190.0, None, ["Rocky body"], None, None),
        "$Codex_Ent_Clypeus_02_Name;": ("Clypeus Margaritus", 11873200, ["CarbonDioxide", "CarbonDioxideRich", "Water", "WaterRich"], 0.275, None, 190.0, None, ["High metal content body"], None, None),
        "$Codex_Ent_Clypeus_03_Name;": ("Clypeus Speculumi", 16202800, ["CarbonDioxide", "CarbonDioxideRich", "Water", "WaterRich"], 0.275, None, 190.0, None, ["Rocky body"], None, "2500ls"),
    },
    "$Codex_Ent_Conchas_Genus_Name;": {
        "$Codex_Ent_Conchas_01_Name;": ("Concha Renibus", 4572400, ["CarbonDioxide", "CarbonDioxideRich", "Water", "WaterRich"], 0.275, None, None, None, ["Rocky body", "High metal content body"], None, None),
        "$Codex_Ent_Conchas_02_Name;": ("Concha Aureolas", 7774700, ["Ammonia"], 0.275, None, None, None, ["Rocky body"], None, None),
        "$Codex_Ent_Conchas_03_Name;": ("Concha Labiata", 2352400, ["CarbonDioxide", "CarbonDioxideRich"], 0.275, None, None, None, ["Rocky body", "High metal content body"], None, None),
        "$Codex_Ent_Conchas_04_Name;": ("Concha Biconcavis", 16777215, ["Nitrogen"], 0.275, None, None, None, ["Rocky body"], None, None),
    },
    "$Codex_Ent_Cone_Name;": {  # No atmos, near center of nebula
        "$Codex_Ent_Cone_Name;": ("Bark Mound", 1471900, ["None"], None, None, None, "Any", None, None, "nebula"),
    },
    "$Codex_Ent_Electricae_Genus_Name;": {
        "$Codex_Ent_Electricae_01_Name;": ("Electricae Pluma", 6284600, ["Helium", "Neon", "NeonRich", "Argon", "ArgonRich"], 0.275, None, None, None, ["Icy body"], None, "AV"),
        "$Codex_Ent_Electricae_02_Name;": ("Electricae Radialem", 6284600, ["Helium", "Neon", "NeonRich", "Argon", "ArgonRich"], 0.275, None, None, None, ["Icy body"], None, "nebula"),
    },
    "$Codex_Ent_Fonticulus_Genus_Name;": {
        "$Codex_Ent_Fonticulus_01_Name;": ("Fonticulua Segmentatus", 19010800, ["Neon", "NeonRich"], 0.275, None, None, None, ["Icy body", "Rocky ice body"], None, None),
        "$Codex_Ent_Fonticulus_02_Name;": ("Fonticulua Campestris", 1000000, ["Argon"], 0.275, None, None, None, ["Icy body", "Rocky ice body"], None, None),
        "$Codex_Ent_Fonticulus_03_Name;": ("Fonticulua Upupam", 5727600, ["ArgonRich"], 0.275, None, None, None, ["Icy body", "Rocky ice body"], None, None),
        "$Codex_Ent_Fonticulus_04_Name;": ("Fonticulua Lapida", 3111000, ["Nitrogen"], 0.275, None, None, None, ["Icy body", "Rocky ice body"], None, None),
        "$Codex_Ent_Fonticulus_05_Name;": ("Fonticulua Fluctus", 20000000, ["Oxygen"], 0.275, None, None, None, ["Icy body", "Rocky ice body"], None, None),
        "$Codex_Ent_Fonticulus_06_Name;": ("Fonticulua Digitos", 1804100, ["Methane", "MethaneRich"], 0.275, None, None, None, ["Icy body", "Rocky ice body"], None, None),
    },
    "$Codex_Ent_Fumerolas_Genus_Name;": {  # Needs femarole geological signal - can add
        "$Codex_Ent_Fumerolas_01_Name;": ("Fumerola Carbosis", 6284600, None, 0.275, None, None, ["carbon", "methane"], None, None, None),
        "$Codex_Ent_Fumerolas_02_Name;": ("Fumerola Extremus", 16202800, None, 0.275, None, None, ["silicate", "iron", "rocky"], None, None, None),
        "$Codex_Ent_Fumerolas_03_Name;": ("Fumerola Nitris", 7500900, None, 0.275, None, None, ["nitrogen", "ammonia"], None, None, None),
        "$Codex_Ent_Fumerolas_04_Name;": ("Fumerola Aquatis", 6284600, None, 0.275, None, None, ["water"], None, None, None),
    },
    "$Codex_Ent_Fungoids_Genus_Name;": {
        "$Codex_Ent_Fungoids_01_Name;": ("Fungoida Setisis", 1670100, ["Ammonia"], 0.275, None, None, None, ["Rocky body", "High metal content body"], None, None),  # "Methane", "MethaneRich", ?
        "$Codex_Ent_Fungoids_02_Name;": ("Fungoida Stabitis", 2680300, ["CarbonDioxide", "CarbonDioxideRich", "Water", "WaterRich"], 0.275, None, None, None, ["Rocky body", "High metal content body"], ["orion-cygnus"], None),
        "$Codex_Ent_Fungoids_03_Name;": ("Fungoida Bullarum", 3703200, ["Argon", "ArgonRich"], 0.275, None, None, None, ["Rocky ice body"], None, None),
        "$Codex_Ent_Fungoids_04_Name;": ("Fungoida Gelata", 3330300, ["CarbonDioxide", "CarbonDioxideRich", "Water", "WaterRich"], 0.275, None, None, None, ["Rocky body", "High metal content body"], None, None),
    },
    "$Codex_Ent_Ground_Struct_Ice_Name;": {  # No atmos, A F G K M S star, < 273K, with Earth, Ammonia, Giant w/life, Water giant, >12kLs
        "$Codex_Ent_Ground_Struct_Ice_Name;": ("Crystalline Shards", 1628800, ["None"], None, 273.0, None, None, None, None, "AFGKMSS"),
    },
    "$Codex_Ent_Osseus_Genus_Name;": {
        "$Codex_Ent_Osseus_01_Name;": ("Osseus Fractus", 4027800, ["CarbonDioxide", "CarbonDioxideRich"], 0.275, 190.0, 180.0, None, ["Rocky body", "High metal content body"], None, None),
        "$Codex_Ent_Osseus_02_Name;": ("Osseus Discus", 12934900, ["Water", "WaterRich"], 0.275, None, None, None, ["Rocky body", "High metal content body"], None, None),
        "$Codex_Ent_Osseus_03_Name;": ("Osseus Spiralis", 2404700, ["Ammonia"], 0.275, None, None, None, ["Rocky body", "High metal content body"], None, None),
        "$Codex_Ent_Osseus_04_Name;": ("Osseus Pumice", 3156300, ["Argon", "ArgonRich", "Methane", "MethaneRich", "Nitrogen"], 0.275, None, None, None, ["Rocky body", "Rocky ice body", "High metal content body"], None, None),
        "$Codex_Ent_Osseus_05_Name;": ("Osseus Cornibus", 1483000, ["CarbonDioxide", "CarbonDioxideRich"], 0.275, 195.0, 180.0, None, ["Rocky body", "High metal content body"], ["perseus"], None),
        "$Codex_Ent_Osseus_06_Name;": ("Osseus Pellebantus", 9739000, ["CarbonDioxide", "CarbonDioxideRich"], 0.275, 195.0, 190.0, None, ["Rocky body", "High metal content body"], None, None),
    },
    "$Codex_Ent_Recepta_Genus_Name;": {
        "$Codex_Ent_Recepta_01_Name;": ("Recepta Umbrux", 12934900, ["SulphurDioxide"], 0.275, None, 132.0, None, ["Icy body", "Rocky ice body", "Rocky body"], None, None),
        "$Codex_Ent_Recepta_02_Name;": ("Recepta Deltahedronix", 16202800, ["SulphurDioxide"], 0.275, None, 132.0, None, ["Icy body", "Rocky body", "High metal content body"], None, None),
        "$Codex_Ent_Recepta_03_Name;": ("Recepta Conditivus", 14313700, ["SulphurDioxide"], 0.275, None, 132.0, None, ["Icy body", "Rocky ice body"], None, None),
    },
    "$Codex_Ent_Seed_Name;": {  # No atmos, volc, near guardian ruins
        "$Codex_Ent_Seed_Name;": ("Roseum Brain Tree", 1593700, ["None"], None, 500.0, 200.0, "Any", None, None, "guardian"),
        "$Codex_Ent_SeedABCD_01_Name;": ("Gypseeum Brain Tree", 1593700, ["None"], None, 300.0, 200.0, "Any", ["Rocky body"], None, "life"),
        "$Codex_Ent_SeedABCD_02_Name;": ("Ostrinum Brain Tree", 1593700, ["None"], None, None, None, "Any", ["Metal rich body", "High metal content body"], None, "guardian+life"),
        "$Codex_Ent_SeedABCD_03_Name;": ("Viride Brain Tree", 1593700, ["None"], None, 270.0, 100.0, "Any", ["Rocky ice body"], None, "guardian+life"),
        "$Codex_Ent_SeedEFGH_01_Name;": ("Aureum Brain Tree", 1593700, ["None"], None, 500.0, 300.0, "Any", ["Metal rich body", "High metal content body"], None, "guardian+life"),
        "$Codex_Ent_SeedEFGH_02_Name;": ("Puniceum Brain Tree", 1593700, ["None"], None, 500.0, 300.0, "Any", ["Metal rich body", "High metal content body"], None, "guardian+life"),
        "$Codex_Ent_SeedEFGH_03_Name;": ("Lindigoticum Brain Tree", 1593700, ["None"], None, 500.0, 300.0, "Any", ["Rocky body", "High metal content body"], None, "guardian+life"),
        "$Codex_Ent_SeedEFGH_Name;": ("Lividum Brain Tree", 1593700, ["None"], None, None, None, "Any", ["Rocky body"], None, "guardian+life"),
    },
    "$Codex_Ent_Shrubs_Genus_Name;": {
        "$Codex_Ent_Shrubs_01_Name;": ("Frutexa Flabellum", 1808900, ["Ammonia"], 0.275, None, None, None, ["Rocky body"], None, None),
        "$Codex_Ent_Shrubs_02_Name;": ("Frutexa Acus", 7774700, ["CarbonDioxide", "CarbonDioxideRich"], 0.275, 190.0, 1.0, None, ["Rocky body"], ["orion-cygnus"], None),
        "$Codex_Ent_Shrubs_03_Name;": ("Frutexa Metallicum", 1632500, ["Ammonia", "CarbonDioxide", "CarbonDioxideRich"], 0.275, 190.0, 1.0, None, ["High metal content body"], None, None),
        "$Codex_Ent_Shrubs_04_Name;": ("Frutexa Flammasis", 10326000, ["Ammonia"], 0.275, None, None, None, ["Rocky body"], ["scutum-centaurus"], None),
        "$Codex_Ent_Shrubs_05_Name;": ("Frutexa Fera", 1632500, ["CarbonDioxide", "CarbonDioxideRich"], 0.275, 190.0, 1.0, None, ["Rocky body"], ["outer"], None),
        "$Codex_Ent_Shrubs_06_Name;": ("Frutexa Sponsae", 5988000, ["Water", "WaterRich"], 0.275, None, None, None, ["Rocky body"], None, None),
        "$Codex_Ent_Shrubs_07_Name;": ("Frutexa Collum", 1639800, ["SulphurDioxide"], 0.275, None, None, None, ["Rocky body"], None, None),
    },
    "$Codex_Ent_Sphere_Name;": {
        "$Codex_Ent_Sphere_Name;": ("Luteolum Anemone", 1499900, None, None, 440.0, 200.0, "Any", ["Rocky body"], None, "B"),
        "$Codex_Ent_SphereABCD_01_Name;": ("Croceum Anemone", 1499900, None, None, 440.0, 200.0, "Any", ["Rocky body"], None, "AB"),
        "$Codex_Ent_SphereABCD_02_Name;": ("Puniceum Anemone", 1499900, None, None, 860.0, 65.0, "Any", ["Icy body", "Rocky ice body"], None, "O"),
        "$Codex_Ent_SphereABCD_03_Name;": ("Roseum Anemone", 1499900, None, None, 440.0, 200.0, "Any", ["Rocky body"], None, "B"),
        "$Codex_Ent_SphereEFGH_01_Name;": ("Rubeum Bioluminescent Anemone", 1499900, None, None, None, 160.0, "Any", ["Metal rich body", "High metal content body"], None, "AB"),
        "$Codex_Ent_SphereEFGH_02_Name;": ("Prasinum Bioluminescent Anemone", 1499900, None, None, None, None, "Any", ["Metal rich body", "Rocky body", "High metal content body"], None, "O"),
        "$Codex_Ent_SphereEFGH_03_Name;": ("Roseum Bioluminescent Anemone", 1499900, None, None, None, 200.0, "Any", ["Metal rich body", "High metal content body"], None, "B"),
        "$Codex_Ent_SphereEFGH_Name;": ("Blatteum Bioluminescent Anemone", 1499900, None, None, None, 220.0, "Any", ["Metal rich body", "High metal content body"], None, "B"),
    },
    "$Codex_Ent_Stratum_Genus_Name;": {
        "$Codex_Ent_Stratum_01_Name;": ("Stratum Excutitus", 2448900, ["CarbonDioxide", "CarbonDioxideRich", "SulphurDioxide"], None, 190.0, 165.0, None, ["Rocky body"], ["orion-cygnus"], None),
        "$Codex_Ent_Stratum_02_Name;": ("Stratum Paleas", 1362000, ["Ammonia", "CarbonDioxide", "CarbonDioxideRich", "Water", "WaterRich"], None, None, 165.0, None, ["Rocky body"], None, None),
        "$Codex_Ent_Stratum_03_Name;": ("Stratum Laminamus", 2788300, ["Ammonia"], None, None, 165.0, None, ["Rocky body"], ["orion-cygnus-1"], None),
        "$Codex_Ent_Stratum_04_Name;": ("Stratum Araneamus", 2448900, ["SulphurDioxide"], None, None, 165.0, None, ["Rocky body"], None, None),
        "$Codex_Ent_Stratum_05_Name;": ("Stratum Limaxus", 1362000, ["CarbonDioxide", "CarbonDioxideRich", "SulphurDioxide"], None, 190.0, 165.0, None, ["Rocky body"], ["scutum-centaurus-core"], None),
        "$Codex_Ent_Stratum_06_Name;": ("Stratum Cucumisis", 16202800, ["CarbonDioxide", "CarbonDioxideRich", "SulphurDioxide"], None, None, 190.0, None, ["Rocky body"], ["carina-sagittarius"], None),
        "$Codex_Ent_Stratum_07_Name;": ("Stratum Tectonicas", 19010800, ["Ammonia", "Oxygen", "CarbonDioxide", "CarbonDioxideRich", "Water", "WaterRich", "SulphurDioxide"], None, None, 165.0, None, ["High metal content body"], None, None),
        "$Codex_Ent_Stratum_08_Name;": ("Stratum Frigus", 2637500, ["CarbonDioxide", "CarbonDioxideRich", "SulphurDioxide"], None, None, 190.0, None, ["Rocky body"], ["perseus"], None),
    },
    "$Codex_Ent_Tube_Name;": {
        "$Codex_Ent_Tube_Name;": ("Roseum Sinuous Tubers", 111300, ["None"], None, 500.0, 200.0, "silicate magme", None, ["core"], None),
        "$Codex_Ent_TubeABCD_01_Name;": ("Prasinum Sinuous Tubers", 1514500, ["None"], None, 500.0, 200.0, "Any", ["Metal rich body", "High metal content body"], ["core"], None),
        "$Codex_Ent_TubeABCD_02_Name;": ("Albidum Sinuous Tubers", 111300, ["None"], None, 500.0, 200.0, "Any", ["Rocky body"], ["core"], None),
        "$Codex_Ent_TubeABCD_03_Name;": ("Caeruleum Sinuous Tubers", 1514500, ["None"], None, 500.0, 200.0, "Any", ["Rocky body"], ["core"], None),
        "$Codex_Ent_TubeEFGH_01_Name;": ("Lindigoticum Sinuous Tubers", 3425600, ["None"], None, 500.0, 200.0, "Any", ["Rocky body"], ["core"], None),
        "$Codex_Ent_TubeEFGH_02_Name;": ("Violaceum Sinuous Tubers", 3425600, ["None"], None, 500.0, 200.0, "Any", ["Metal rich body", "High metal content body", "Rocky body"], ["core"], None),
        "$Codex_Ent_TubeEFGH_03_Name;": ("Viride Sinuous Tubers", 3425600, ["None"], None, 500.0, 200.0, "Any", ["Rocky body", "High metal content body"], ["core"], None),
        "$Codex_Ent_TubeEFGH_Name;": ("Blatteum Sinuous Tubers", 3425600, ["None"], None, 500.0, 200.0, "Any", ["Metal rich body", "High metal content body", "Rocky body"], ["core"], None),
    },
    "$Codex_Ent_Tubus_Genus_Name;": {
        "$Codex_Ent_Tubus_01_Name;": ("Tubus Conifer", 2415500, ["CarbonDioxide", "CarbonDioxideRich"], 0.155, 190.0, 160.0, None, ["Rocky body"], ["perseus"], None),
        "$Codex_Ent_Tubus_02_Name;": ("Tubus Sororibus", 5727600, ["Ammonia", "CarbonDioxide", "CarbonDioxideRich"], 0.155, 190.0, 160.0, None, ["High metal content body"], None, None),
        "$Codex_Ent_Tubus_03_Name;": ("Tubus Cavas", 11873200, ["CarbonDioxide", "CarbonDioxideRich"], 0.155, 190.0, 160.0, None, ["Rocky body"], ["scutum-centaurus"], None),
        "$Codex_Ent_Tubus_04_Name;": ("Tubus Rosarium", 2637500, ["Ammonia"], 0.155, None, None, None, ["Rocky body"], None, None),
        "$Codex_Ent_Tubus_05_Name;": ("Tubus Compagibus", 7774700, ["CarbonDioxide", "CarbonDioxideRich"], 0.155, 190.0, 160.0, None, ["Rocky body"], ["carina-sagittarius"], None),
    },
    "$Codex_Ent_Tussocks_Genus_Name;": {
        "$Codex_Ent_Tussocks_01_Name;": ("Tussock Pennata", 5853800, ["CarbonDioxide", "CarbonDioxideRich"], 0.275, 155.0, 145.0, None, ["Rocky body"], ["carina-sagittarius-1", "perseus-1"], None),
        "$Codex_Ent_Tussocks_02_Name;": ("Tussock Ventusa", 3227700, ["CarbonDioxide", "CarbonDioxideRich"], 0.275, 160.0, 155.0, None, ["Rocky body"], ["carina-sagittarius-1", "perseus-1"], None),
        "$Codex_Ent_Tussocks_03_Name;": ("Tussock Ignis", 1849000, ["CarbonDioxide", "CarbonDioxideRich"], 0.275, 170.0, 160.0, None, ["Rocky body"], ["carina-sagittarius", "perseus"], None),
        "$Codex_Ent_Tussocks_04_Name;": ("Tussock Cultro", 1766600, ["Ammonia"], 0.275, None, None, None, ["Rocky body", "High metal content body"], ["orion-cygnus"], None),
        "$Codex_Ent_Tussocks_05_Name;": ("Tussock Catena", 1766600, ["Ammonia"], 0.275, None, None, None, ["Rocky body", "High metal content body"], ["scutum-centaurus-core"], None),
        "$Codex_Ent_Tussocks_06_Name;": ("Tussock Pennatis", 1000000, ["CarbonDioxide", "CarbonDioxideRich"], 0.275, None, None, None, ["Rocky body", "High metal content body"], ["outer"], None),
        "$Codex_Ent_Tussocks_07_Name;": ("Tussock Serrati", 4447100, ["CarbonDioxide", "CarbonDioxideRich"], 0.275, 175.0, 170.0, None, ["Rocky body", "High metal content body"], ["carina-sagittarius-1", "perseus-1"], None),
        "$Codex_Ent_Tussocks_08_Name;": ("Tussock Albata", 3252500, ["CarbonDioxide", "CarbonDioxideRich"], 0.275, 180.0, 175.0, None, ["Rocky body", "High metal content body"], ["carina-sagittarius", "perseus"], None),
        "$Codex_Ent_Tussocks_09_Name;": ("Tussock Propagito", 1000000, ["CarbonDioxide", "CarbonDioxideRich"], 0.275, None, None, None, ["Rocky body", "High metal content body"], ["scutum-centaurus"], None),
        "$Codex_Ent_Tussocks_10_Name;": ("Tussock Divisa", 1766600, ["Ammonia"], 0.275, None, None, None, ["Rocky body", "High metal content body"], ["perseus"], None),
        "$Codex_Ent_Tussocks_11_Name;": ("Tussock Caputus", 3472400, ["CarbonDioxide", "CarbonDioxideRich"], 0.275, 190.0, 180.0, None, ["Rocky body", "High metal content body"], ["carina-sagittarius", "perseus"], None),
        "$Codex_Ent_Tussocks_12_Name;": ("Tussock Triticum", 7774700, ["CarbonDioxide", "CarbonDioxideRich"], 0.275, 195.0, 190.0, None, ["Rocky body", "High metal content body"], ["carina-sagittarius-1", "perseus-1"], None),
        "$Codex_Ent_Tussocks_13_Name;": ("Tussock Stigmasis", 19010800, ["SulphurDioxide"], 0.275, None, None, None, ["Rocky body"], None, None),
        "$Codex_Ent_Tussocks_14_Name;": ("Tussock Virgam", 14313700, ["Water", "WaterRich"], 0.275, None, None, None, ["Rocky body", "High metal content body"], None, None),
        "$Codex_Ent_Tussocks_15_Name;": ("Tussock Capillum", 7025800, ["Argon", "ArgonRich", "Methane", "MethaneRich"], 0.275, None, None, None, ["Rocky ice body"], None, None),
    },
    "$Codex_Ent_Vents_Name;": {  # Metal rich, no atmos, A star, with one of (earth-like, ammonia, giant /w life, water giant)
        "$Codex_Ent_Vents_Name;": ("Amphora Plant", 3626400, ["None"], None, None, None, ["volcanism"], ["Metal rich body"], None, "A+life"),
    },
}

region_map = {
    "orion-cygnus": [1, 2, 3, 4, 7, 8, 15, 16, 17, 18, 35],
    "orion-cygnus-1": [2, 3, 4, 7, 8, 15, 16, 17, 18, 35],
    "carina-sagittarius": [1, 2, 3, 4, 9, 18, 19, 20, 21, 22, 23, 40],
    "carina-sagittarius-1": [2, 3, 4, 9, 18, 19, 20, 21, 22, 23, 40],
    "scutum-centaurus": [1, 4, 9, 10, 11, 12, 18, 24, 25, 26, 42, 28],
    "scutum-centaurus-core": [9, 10, 11, 12, 18, 24, 25, 26, 42, 28],
    "outer": [5, 6, 13, 14, 27, 29, 31, 41, 37],
    "perseus": [1, 2, 3, 4, 7, 15, 30, 32, 33, 34, 36, 38, 39],
    "perseus-1": [2, 3, 4, 7, 15, 30, 32, 33, 34, 36, 38, 39],
    "core": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 15, 16, 17, 18, 19]
}

guardian_sectors = [
    "Synuefe",
    "Col 173 Sector",
    "Vela Dark Region",
    "IC 2391 Sector",
]

# journal_id: (localized name, base value, atmosphere, maximum gravity, maximum temp, minimum temp, volcanism, planet, extra)
bio_codex_map = {
    "$Codex_Ent_Aleoids_Genus_Name;": {
        "$Codex_Ent_Aleoids_01_",
        "$Codex_Ent_Aleoids_02_",
        "$Codex_Ent_Aleoids_03_",
        "$Codex_Ent_Aleoids_04_",
        "$Codex_Ent_Aleoids_05_",
    },
    "$Codex_Ent_Bacterial_Genus_Name;": {
        "$Codex_Ent_Bacterial_01_",
        "$Codex_Ent_Bacterial_02_",
        "$Codex_Ent_Bacterial_03_",
        "$Codex_Ent_Bacterial_04_",
        "$Codex_Ent_Bacterial_05_",
        "$Codex_Ent_Bacterial_06_",
        "$Codex_Ent_Bacterial_07_",
        "$Codex_Ent_Bacterial_08_",
        "$Codex_Ent_Bacterial_09_",
        "$Codex_Ent_Bacterial_10_",
        "$Codex_Ent_Bacterial_11_",
        "$Codex_Ent_Bacterial_12_",
        "$Codex_Ent_Bacterial_13_",
    },
    "$Codex_Ent_Cactoid_Genus_Name;": {
        "$Codex_Ent_Cactoid_01_",
        "$Codex_Ent_Cactoid_02_",
        "$Codex_Ent_Cactoid_03_",
        "$Codex_Ent_Cactoid_04_",
        "$Codex_Ent_Cactoid_05_",
    },
    "$Codex_Ent_Clypeus_Genus_Name;": {
        "$Codex_Ent_Clypeus_01_",
        "$Codex_Ent_Clypeus_02_",
        "$Codex_Ent_Clypeus_03_",
    },
    "$Codex_Ent_Conchas_Genus_Name;": {
        "$Codex_Ent_Conchas_01_",
        "$Codex_Ent_Conchas_02_",
        "$Codex_Ent_Conchas_03_",
        "$Codex_Ent_Conchas_04_",
    },
    "$Codex_Ent_Cone_Name;": {  # No atmos, near center of nebula
        "$Codex_Ent_Cone_"
    },
    "$Codex_Ent_Electricae_Genus_Name;": {
        "$Codex_Ent_Electricae_01_",
        "$Codex_Ent_Electricae_02_",
    },
    "$Codex_Ent_Fonticulus_Genus_Name;": {
        "$Codex_Ent_Fonticulus_01_",
        "$Codex_Ent_Fonticulus_02_",
        "$Codex_Ent_Fonticulus_03_",
        "$Codex_Ent_Fonticulus_04_",
        "$Codex_Ent_Fonticulus_05_",
        "$Codex_Ent_Fonticulus_06_",
    },
    "$Codex_Ent_Fumerolas_Genus_Name;": {  # Needs femarole geological signal - can add
        "$Codex_Ent_Fumerolas_01_",
        "$Codex_Ent_Fumerolas_02_",
        "$Codex_Ent_Fumerolas_03_",
        "$Codex_Ent_Fumerolas_04_",
    },
    "$Codex_Ent_Fungoids_Genus_Name;": {
        "$Codex_Ent_Fungoids_01_",
        "$Codex_Ent_Fungoids_02_",
        "$Codex_Ent_Fungoids_03_",
        "$Codex_Ent_Fungoids_04_",
    },
    "$Codex_Ent_Ground_Struct_Ice_Name;": {  # No atmos, A F G K M S star, < 273K, with Earth, Ammonia, Giant w/life, Water giant, >12kLs
        "$Codex_Ent_Ground_Struct_Ice_"
    },
    "$Codex_Ent_Osseus_Genus_Name;": {
        "$Codex_Ent_Osseus_01_",
        "$Codex_Ent_Osseus_02_",
        "$Codex_Ent_Osseus_03_",
        "$Codex_Ent_Osseus_04_",
        "$Codex_Ent_Osseus_05_",
        "$Codex_Ent_Osseus_06_",
    },
    "$Codex_Ent_Recepta_Genus_Name;": {
        "$Codex_Ent_Recepta_01_",
        "$Codex_Ent_Recepta_02_",
        "$Codex_Ent_Recepta_03_",
    },
    "$Codex_Ent_Seed_Name;": {  # No atmos, volc, near guardian ruins
        "$Codex_Ent_Seed",
        "$Codex_Ent_SeedABCD_01_",
        "$Codex_Ent_SeedABCD_02_",
        "$Codex_Ent_SeedABCD_03_",
        "$Codex_Ent_SeedEFGH_01_",
        "$Codex_Ent_SeedEFGH_02_",
        "$Codex_Ent_SeedEFGH_03_",
        "$Codex_Ent_SeedEFGH_",
    },
    "$Codex_Ent_Shrubs_Genus_Name;": {
        "$Codex_Ent_Shrubs_01_",
        "$Codex_Ent_Shrubs_02_",
        "$Codex_Ent_Shrubs_03_",
        "$Codex_Ent_Shrubs_04_",
        "$Codex_Ent_Shrubs_05_",
        "$Codex_Ent_Shrubs_06_",
        "$Codex_Ent_Shrubs_07_",
    },
    "$Codex_Ent_Sphere_Name;": {
        "$Codex_Ent_Sphere_",
        "$Codex_Ent_SphereABCD_01_",
        "$Codex_Ent_SphereABCD_02_",
        "$Codex_Ent_SphereABCD_03_",
        "$Codex_Ent_SphereEFGH_01_",
        "$Codex_Ent_SphereEFGH_02_",
        "$Codex_Ent_SphereEFGH_03_",
        "$Codex_Ent_SphereEFGH_",
    },
    "$Codex_Ent_Stratum_Genus_Name;": {
        "$Codex_Ent_Stratum_01_",
        "$Codex_Ent_Stratum_02_",
        "$Codex_Ent_Stratum_03_",
        "$Codex_Ent_Stratum_04_",
        "$Codex_Ent_Stratum_05_",
        "$Codex_Ent_Stratum_06_",
        "$Codex_Ent_Stratum_07_",
        "$Codex_Ent_Stratum_08_",
    },
    "$Codex_Ent_Tube_Name;": {
        "$Codex_Ent_Tube_",
        "$Codex_Ent_TubeABCD_01_",
        "$Codex_Ent_TubeABCD_02_",
        "$Codex_Ent_TubeABCD_03_",
        "$Codex_Ent_TubeEFGH_01_",
        "$Codex_Ent_TubeEFGH_02_",
        "$Codex_Ent_TubeEFGH_03_",
        "$Codex_Ent_TubeEFGH_",
    },
    "$Codex_Ent_Tubus_Genus_Name;": {
        "$Codex_Ent_Tubus_01_",
        "$Codex_Ent_Tubus_02_",
        "$Codex_Ent_Tubus_03_",
        "$Codex_Ent_Tubus_04_",
        "$Codex_Ent_Tubus_05_",
    },
    "$Codex_Ent_Tussocks_Genus_Name;": {
        "$Codex_Ent_Tussocks_01_",
        "$Codex_Ent_Tussocks_02_",
        "$Codex_Ent_Tussocks_03_",
        "$Codex_Ent_Tussocks_04_",
        "$Codex_Ent_Tussocks_05_",
        "$Codex_Ent_Tussocks_06_",
        "$Codex_Ent_Tussocks_07_",
        "$Codex_Ent_Tussocks_08_",
        "$Codex_Ent_Tussocks_09_",
        "$Codex_Ent_Tussocks_10_",
        "$Codex_Ent_Tussocks_11_",
        "$Codex_Ent_Tussocks_12_",
        "$Codex_Ent_Tussocks_13_",
        "$Codex_Ent_Tussocks_14_",
        "$Codex_Ent_Tussocks_15_",
    },
    "$Codex_Ent_Vents_Name;": {
        "$Codex_Ent_Vents_",
    },
}


def get_species_from_codex(name: str):
    for genus, search_set in bio_codex_map.items():
        for search in search_set:
            if name.startswith(search):
                for species, _ in bio_types[genus].items():
                    if species.startswith(search):
                        return genus, species
