data = [
    'Aquila Dark Region Sector',
    'B133 Sector',
    'B352 Sector',
    'B92 Sector',
    'Barnard\'s Loop Sector',
    'Bubble Sector',
    'California Sector',
    'Cat\'s Paw Sector',
    'Cave Sector',
    'Cepheus Dark Region Sector',
    'Chamaeleon Sector',
    'Coalsack Dark Region Sector',
    'Cocoon Sector',
    'Cone Sector',
    'Corona Australis Dark Region Sector',
    'Crab Sector',
    'Crescent Sector',
    'Eagle Sector',
    'Elephant\'s Trunk Sector',
    'Eta Carina Sector',
    'Fine Ring Sector',
    'Flame Sector',
    'Flaming Star Sector',
    'G2 Dust Cloud Sector',
    'Heart Sector',
    'Helix Sector',
    'Hind Sector',
    'Horsehead Dark Region Sector',
    'Horsehead Sector',
    'IC 4604 Sector',
    'Iris Sector',
    'Jellyfish Sector',
    'Lagoon Sector',
    'LBN 623 Sector',
    'Lupus Dark Region Sector',
    'Lupus Dark Region B Sector',
    'Messier 78 Sector',
    'Monkey Head Sector',
    'Musca Dark Region Sector',
    'NGC 1333 Sector',
    'NGC 1491 Sector',
    'NGC 1931 Sector',
    'NGC 281 Sector',
    'NGC 3199 Sector',
    'NGC 5367 Sector',
    'NGC 6188 Sector',
    'NGC 6357 Sector',
    'NGC 6820 Sector',
    'NGC 7538 Sector',
    'NGC 7822 Sector',
    'North America Sector',
    'Omega Sector',
    'Ophiuchus Dark Region Sector',
    'Ophiuchus Dark Region B Sector',
    'Ophiuchus Dark Region C Sector',
    'Orion Dark Region Sector',
    'Orion Sector',
    'Parrot\'s Head Sector',
    'Pelican Sector',
    'Pencil Sector',
    'Perseus Dark Region Sector',
    'Pipe (Bowl) Sector',
    'Pipe (Stem) Sector',
    'Pleiades Sector',
    'Puppis Dark Region Sector',
    'Puppis Dark Region B Sector',
    'Rho Ophiuchi Sector',
    'Ring Sector',
    'Rosette Sector',
    'Running Man Sector',
    'Scorpius Dark Region Sector',
    'Scutum Dark Region Sector',
    'Seagull Sector',
    'Skull and Crossbones Sector',
    'Skull Sector',
    'Snake Sector',
    'Soul Sector',
    'Statue of Liberty Sector',
    'Struve\'s Lost Sector',
    'Taurus Dark Region Sector',
    'Trifid Sector',
    'Trifid of the North Sector',
    'Veil East Sector',
    'Veil West Sector',
    'Vela Dark Region Sector',
    'Vulpecula Dark Region Sector',
    'Witch Head Sector',
]
